apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: shaked-python-comp
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: shaked-python-comp
    app.kubernetes.io/part-of: shaked-new-app2
  name: shaked-python-comp
spec:
  replicas: 0
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: python-app
      app.kubernetes.io/instance: shaked-python-comp
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: python-app
        app.kubernetes.io/instance: shaked-python-comp
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/rh-ee-saviv-tenant/shaked-new-app2/shaked-python-comp@sha256:4480487a4f9c7a17c8d3cccc54febcd7752c3852b31de577c865dbc1381f75d4
        name: my-python
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
