apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: shaked-python-comp
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: shaked-python-comp
    app.kubernetes.io/part-of: shaked-new-app2
  name: shaked-python-compsbmg
spec:
  path: /
  port:
    targetPort: 8081
  to:
    kind: Service
    name: shaked-python-comp
    weight: null
status: {}
